version: '3.8'

services:
  app:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - "${DOCKER_APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/saas
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data: 