version: '3.8'

services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - "${DOCKER_APP_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/saas
      - NEXT_PUBLIC_APP_URL=http://localhost:${DOCKER_APP_PORT:-3000}
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: mongo:6
    ports:
      - "${DOCKER_MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data: 